name: /opt/anaconda3/envs/chapter22
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.7.0=py39hca03da5_0
  - appnope=0.1.2=py39hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h80987f9_1
  - asttokens=3.0.0=py39hca03da5_0
  - async-lru=2.0.4=py39hca03da5_0
  - attrs=24.3.0=py39hca03da5_0
  - babel=2.16.0=py39hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39hca03da5_0
  - bleach=6.2.0=py39hca03da5_0
  - brotli-python=1.0.9=py39h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - certifi=2025.4.26=py39hca03da5_0
  - cffi=1.17.1=py39h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py39hca03da5_0
  - debugpy=1.8.11=py39h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h313beb8_0
  - h11=0.16.0=py39hca03da5_0
  - httpcore=1.0.9=py39hca03da5_0
  - httpx=0.28.1=py39hca03da5_0
  - idna=3.7=py39hca03da5_0
  - importlib-metadata=8.5.0=py39hca03da5_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.29.5=py39hca03da5_1
  - ipython=8.15.0=py39hca03da5_0
  - jedi=0.19.2=py39hca03da5_0
  - jinja2=3.1.6=py39hca03da5_0
  - json5=0.9.25=py39hca03da5_0
  - jsonschema=4.23.0=py39hca03da5_0
  - jsonschema-specifications=2023.7.1=py39hca03da5_0
  - jupyter-lsp=2.2.5=py39hca03da5_0
  - jupyter_client=8.6.3=py39hca03da5_0
  - jupyter_core=5.7.2=py39hca03da5_0
  - jupyter_events=0.12.0=py39hca03da5_0
  - jupyter_server=2.15.0=py39hca03da5_0
  - jupyter_server_terminals=0.5.3=py39hca03da5_0
  - jupyterlab=4.3.4=py39hca03da5_0
  - jupyterlab_pygments=0.3.0=py39hca03da5_0
  - jupyterlab_server=2.27.3=py39hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.18=h1a28f6b_0
  - markupsafe=3.0.2=py39h80987f9_0
  - matplotlib-inline=0.1.6=py39hca03da5_0
  - mistune=3.1.2=py39hca03da5_0
  - nbclient=0.10.2=py39hca03da5_0
  - nbconvert-core=7.16.6=py39hca03da5_0
  - nbformat=5.10.4=py39hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py39hca03da5_0
  - notebook-shim=0.2.4=py39hca03da5_0
  - openssl=3.0.16=h02f6b3c_0
  - overrides=7.4.0=py39hca03da5_0
  - packaging=24.2=py39hca03da5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py39hca03da5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py39hca03da5_0
  - prometheus_client=0.21.1=py39hca03da5_0
  - prompt-toolkit=3.0.43=py39hca03da5_0
  - psutil=5.9.0=py39h80987f9_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.23=h99c0cbc_0
  - python-dateutil=2.9.0post0=py39hca03da5_2
  - python-fastjsonschema=2.20.0=py39hca03da5_0
  - python-json-logger=3.2.1=py39hca03da5_0
  - pyyaml=6.0.2=py39h80987f9_0
  - pyzmq=26.2.0=py39h313beb8_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py39hca03da5_0
  - requests=2.32.3=py39hca03da5_1
  - rfc3339-validator=0.1.4=py39hca03da5_0
  - rfc3986-validator=0.1.1=py39hca03da5_0
  - rpds-py=0.22.3=py39h2aea54e_0
  - send2trash=1.8.2=py39hca03da5_1
  - setuptools=78.1.1=py39hca03da5_0
  - six=1.17.0=py39hca03da5_0
  - sniffio=1.3.0=py39hca03da5_0
  - soupsieve=2.5=py39hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py39hca03da5_0
  - tinycss2=1.4.0=py39hca03da5_0
  - tk=8.6.14=h6ba3021_1
  - tomli=2.0.1=py39hca03da5_0
  - tornado=6.5.1=py39h80987f9_0
  - traitlets=5.14.3=py39hca03da5_0
  - typing-extensions=4.12.2=py39hca03da5_0
  - typing_extensions=4.12.2=py39hca03da5_0
  - urllib3=2.3.0=py39hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hca03da5_1
  - websocket-client=1.8.0=py39hca03da5_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=py39hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - pip:
      - adagio==0.2.6
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - alembic==1.16.1
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - async-timeout==5.0.1
      - blinker==1.9.0
      - cachetools==5.5.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.0
      - coreforecast==0.0.16
      - cycler==0.12.1
      - darts==0.35.0
      - databricks-sdk==0.56.0
      - docker==7.1.0
      - fastapi==0.115.12
      - filelock==3.18.0
      - flask==3.1.1
      - fonttools==4.58.2
      - frozenlist==1.7.0
      - fs==2.4.16
      - fsspec==2025.5.1
      - fugue==0.9.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - gunicorn==23.0.0
      - holidays==0.74
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - lightning-utilities==0.14.3
      - llvmlite==0.43.0
      - mako==1.3.10
      - matplotlib==3.9.4
      - mlflow==3.1.0
      - mlflow-skinny==3.1.0
      - mpmath==1.3.0
      - multidict==6.4.4
      - narwhals==1.42.0
      - networkx==3.2.1
      - nfoursid==1.0.1
      - numba==0.60.0
      - numpy==2.0.2
      - opentelemetry-api==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - pandas==2.3.0
      - patsy==1.0.1
      - pillow==11.2.1
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pyod==2.0.5
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - rsa==4.9.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - shap==0.48.0
      - slicer==0.0.8
      - smmap==5.0.2
      - sqlalchemy==2.0.41
      - sqlparse==0.5.3
      - starlette==0.46.2
      - statsforecast==2.0.1
      - statsmodels==0.14.4
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - torch==2.7.1
      - torchmetrics==1.7.2
      - tqdm==4.67.1
      - triad==0.9.8
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - utilsforecast==0.2.12
      - uvicorn==0.34.3
      - werkzeug==3.1.3
      - xarray==2024.7.0
      - xgboost==2.1.4
      - yarl==1.20.1
prefix: /opt/anaconda3/envs/chapter22
